# Note on validation: In validating this file, destination related values along
# with anything not source device related gets validated when the program first
# runs. But - because source devices may not be ready or present when the run
# starts - all source device related value validation is postponed till the
# first command received that actually involves that source device. This could
# result in delayed detection of errors liked mispelled or incorrect values
# which, for most other programs, will get detected when the program first runs.

# When an option value is a list the entries should be separated by commas. When
# there is only one item a trailing comma is required. (For lists with more than
# one item the trailing comma is not required but it is a good idea to put it in
# anyway in case the list gets edited in future and becomes a one item list).

#==== GLOBALS (System-wide options) ====

[DEFAULT]

links: mtp_ubuntu,usb_ubuntu,android_sshelper,local_fs,
devices: ph_s7,ph_s8,ph_p3,ph_m7,test,akaso_ek7000,localhost,
ops: import,dryrun,export,cleanup,admin,
# No overall limit on parallel runs
# NOTE: Omitted MAX_PARALLEL value means no upper limit, zero means no parallels
global_max_parallels:

[local_dirs]

# Softlink, used to shorten file locator lengths (see the line below)
inbox_dir: /IN
#inbox_dir: %(home_dir)s/uncloud/inbox
outbox_dir: %(home_dir)s/uncloud/outbox
catalog_dir: %(home_dir)s/uncloud/catalog
catalog_index_dir: %(home_dir)s/uncloud/catalog_index
commands_dir: %(home_dir)s/uncloud/commands
responses_dir: %(home_dir)s/uncloud/responses
trash_list_dir: %(home_dir)s/uncloud/trash_list

[file_category_for_file_extension]

jpg: picture
jpeg: picture
png: picture
gif: picture
mp4: video
mpeg: video
wmv: video
3gp: video
webm: video
mov: video
mp3: music
# Note .amr files contain voicemails
amr: music
opus: music
mmf: music
au: music
aac: music
wav: music
ogg: music
oga: music
mogg: music
wma: music
doc: document
txt: document
pdf: document
kml: document
kmz: document
ppt: document
xls: document
xlsx: document
odt: document

#==== LINK (i.e. connection protocol) specific options ====

[mtp_ubuntu]

# Mtp links support * in the file_system_base_name, matching it to names found
file_system_base: /run/user/*/gvfs
# While the MTP link is capable of handling more than one device - if they are
# connected to different USB ports - it is difficult to identify which device is
# connected at which port. Accordingly we restrict it to one run at a time
max_parallels: 1

[usb_ubuntu]

# USB links support * in the file_system_base_name, matching it to names found
file_system_base: /media/%(user)s/*
# The USB Ubuntu link has no limit on the number of parallel runs
max_parallels:

[android_sshelper]

mnt_pt: /mnt/%(start_time)s
# The ssh Helper link has no limit on the number of parallel runs
max_parallels:

[local_fs]

file_system_base: %(home_dir)s
# The Local File System link has no limit on the number of parallel runs
max_parallels: 1

#==== DEVICE (and device/link) specific options ====

# Device options are either link specific and are named linkname__optionname
# or are link-independent and are named device__optionname.

[ph_s7]

device__links: mtp_ubuntu,android_sshelper,
device__ops: import,dryrun,export,cleanup,admin,
# This device has no link independent limit on the number of parallel runs
device__max_parallels:
# Device files are copied to inbox
device__file_import_mode: copy
mtp_ubuntu__mnt_dir_device_path_pairs: Card,/storage/3536-3134/,Phone,/storage/emulated/0/,
# The MTP Ubuntu link only allows one host acess - and hence one run - at a time
mtp_ubuntu__max_parallels: 1
android_sshelper__ip: 172.16.0.6
android_sshelper__port: 2222
android_sshelper__user: %(user)s
android_sshelper__bonjour_device_name: Samsung_Galaxy_S7
android_sshelper__to_mount_pairs: /storage,ph_s7/sdcard,/storage/emulated/0,ph_s7/internal,
android_sshelper__mnt_dir_device_path_pairs: ph_s7/sdcard/3536-3134/,/storage/3536-3134/,ph_s7/internal/,/storage/emulated/0/,
# Though more than one ssh Helper run is possible,that can lead to unpredictable operation due to two or more
# runs trying to access the source file system. Accordingly we restrict it to one run at a time
android_sshelper__max_parallels: 1

[ph_s8]

device__links: mtp_ubuntu,android_sshelper,
device__ops: import,dryrun,export,cleanup,admin,
# This device has no link independent limit on the number of parallel runs
device__max_parallels:
# Device files are copied to inbox
device__file_import_mode: copy
mtp_ubuntu__mnt_dir_device_path_pairs: Card,/storage/3736-3861/,Phone,/storage/emulated/0/,
# The MTP Ubuntu link only allows one host acess - and hence one run - at a time
mtp_ubuntu__max_parallels: 1
android_sshelper__ip: 172.16.0.16
android_sshelper__port: 2222
android_sshelper__user: %(user)s
android_sshelper__bonjour_device_name: Galaxy_S8
android_sshelper__to_mount_pairs: /storage,ph_s8/sdcard,/storage/emulated/0,ph_s8/internal,
android_sshelper__mnt_dir_device_path_pairs: ph_s8/sdcard/3736-3861/,/storage/3736-3861/,ph_s8/internal/,/storage/emulated/0/,
# Though more than one ssh Helper run is possible,that can lead to unpredictable operation due to two or more
# runs trying to access the source file system. Accordingly we restrict it to one run at a time
android_sshelper__max_parallels: 1

[ph_p3]

device__links: mtp_ubuntu,android_sshelper,
device__ops: import,dryrun,export,cleanup,admin,
# This device has no link independent limit on the number of parallel runs
device__max_parallels:
# Device files are copied to inbox
device__file_import_mode: copy
mtp_ubuntu__mnt_dir_device_path_pairs: Phone,/storage/emulated/0/,
# The MTP Ubuntu link only allows one host acess - and hence one run - at a time
mtp_ubuntu__max_parallels: 1
android_sshelper__ip: 172.16.0.18
android_sshelper__port: 2222
android_sshelper__user: %(user)s
android_sshelper__bonjour_device_name: Pixel_2_XL
android_sshelper__to_mount_pairs: /storage/emulated/0,ph_p3/internal,
android_sshelper__mnt_dir_device_path_pairs: ph_p3/internal/,/storage/emulated/0/,
# Though more than one ssh Helper run is possible,that can lead to unpredictable operation due to two or more
# runs trying to access the source file system. Accordingly we restrict it to one run at a time
android_sshelper__max_parallels: 1

[ph_m7]

device__links: mtp_ubuntu,android_sshelper,
device__ops: import,dryrun,export,cleanup,admin,
# This device has no link independent limit on the number of parallel runs
device__max_parallels:
# Device files are copied to inbox
device__file_import_mode: copy
mtp_ubuntu__mnt_dir_device_path_pairs: Card,/storage/0298-D5A9/,Phone,/storage/emulated/0/,
# The MTP Ubuntu link only allows one host acess - and hence one run - at a time
mtp_ubuntu__max_parallels: 1
android_sshelper__ip: 172.16.0.25
android_sshelper__port: 2222
android_sshelper__user: %(user)s
android_sshelper__bonjour_device_name: moto_g(7)
android_sshelper__to_mount_pairs: /storage,ph_m7/sdcard,/storage/emulated/0,ph_m7/internal,
android_sshelper__mnt_dir_device_path_pairs: ph_m7/sdcard/0298-D5A9/,/storage/0298-D5A9/,ph_m7/internal/,/storage/emulated/0/,
# Though more than one ssh Helper run is possible,that can lead to unpredictable operation due to two or more
# runs trying to access the source file system. Accordingly we restrict it to one run at a time
android_sshelper__max_parallels: 1

[test]

device__links: mtp_ubuntu,android_sshelper,
device__ops: import,dryrun,export,cleanup,admin,
# This device has no link independent limit on the number of parallel runs
device__max_parallels:
# Device files are copied to inbox
device__file_import_mode: copy
mtp_ubuntu__mnt_dir_device_path_pairs: Card,/storage/3536-3134/,Phone,/storage/emulated/0/,
# The MTP Ubuntu link only allows one host acess - and hence one run - at a time
mtp_ubuntu__max_parallels: 1
android_sshelper__ip: 172.16.0.6
android_sshelper__port: 2222
android_sshelper__user: %(user)s
android_sshelper__bonjour_device_name: Samsung_Galaxy_S7
android_sshelper__to_mount_pairs: /storage,test/sdcard,/storage/emulated/0,test/internal
android_sshelper__mnt_dir_device_path_pairs: test/sdcard/3536-3134/,/storage/3536-3134/,test/internal/,/storage/emulated/0/,
# Though more than one ssh Helper run is possible,that can lead to unpredictable operation due to two or more
# runs trying to access the source file system. Accordingly we restrict it to one run at a time
android_sshelper__max_parallels: 1

[akaso_ek7000]

device__links: usb_ubuntu,
device__ops: import,dryrun,export,cleanup,admin,
# This device has no link independent limit on the number of parallel runs
device__max_parallels:
# Device files are copied to inbox
device__file_import_mode: copy
usb_ubuntu__mnt_dir_device_path_pairs: PHOTO,/PHOTO,VIDEO,/VIDEO
# The USB Ubuntu link only allows one host acess - and hence one run - at a time
usb_ubuntu__max_parallels: 1

# NOTE: The device name used in files for the 'localhost' device is not
# 'localhost' but the host computer name
[localhost]

device__links: local_fs,
device__ops: import,dryrun,export,cleanup,admin,
# This device has no link independent limit on the number of parallel runs
device__max_parallels:
# Device files are not copied or moved to inbox
device__file_import_mode: none
device__exclude_dirs: %(home_dir)s/uncloud,
device__exclude_files:
device__include_files:
local_fs__mnt_dir_device_path_pairs: %(home_dir)s,%(home_dir)s,
# Though more than one Local File System run is possible,that can lead to unpredictable operation due to two or more
# runs trying to access the source file system. Accordingly we restrict it to one run at a time
local_fs__max_parallels: 1
